### ISSUE TITLE
`azd init` command is not specific

### ISSUE THREAD

**Issue by NanaXiong00** [john0isaac/flask-webapp-mysql-db#10]
**Describe the issue:**
When running `azd init` command, there is no `john0isaac/flask-webapp-mysql-db` template in the prompt list.
<img width="700" alt="4" src="https://github.com/john0isaac/flask-webapp-mysql-db/assets/138103031/79de11c2-af98-40e7-9b9c-f766c5c766c8">

**Suggestion:**
Update to `azd init -t john0isaac/flask-webapp-mysql-db`.

@john0isaac and @hemarina for notification.

**Comment by john0isaac** [comment]
You are supposed to run the command after you follow the previous steps of cloning the repository.

the purpose of the command is to initialize an environment.



![image](https://github.com/john0isaac/flask-webapp-mysql-db/assets/64026625/3d7e0093-f385-44a5-a2a7-cb05f168fd1e)

**Comment by NanaXiong00** [comment]
@john0isaac 
For the unity of azd templates, it is recommended to change `azd init` to `azd init -t john0isaac/flask-webapp-mysql-db`.

[Local Development](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#local-development) and [Deployment](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#deployment) should be two parts that can be executed independently.

In the [Deployment](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#deployment) section, use `azd init -t john0isaac/flask-webapp-mysql-db` to initialize the project in the current directory, use `azd up` provision and deploy to Azure.

**Comment by john0isaac** [comment]
@NanaXiong00 done ✅
