### ISSUE TITLE
Lack of instructions for MySQL connection configuration

### ISSUE THREAD

**Issue by NanaXiong00** [john0isaac/flask-webapp-mysql-db#11]
**Describe the issue:**
Follow the steps of [README.md](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#local-development), after running `flask run --reload`, open http://127.0.0.1:5000/ and clicking `post a venue`, the web page displays "Sorry...".
<img width="750" alt="7" src="https://github.com/john0isaac/flask-webapp-mysql-db/assets/138103031/c7b4e179-ac00-4346-bfa4-02ea0feb30e8">

**Repro Steps:**
- windows
1. Download the project starter code locally.
2. Initialize and activate a virtualenv using:
```
pip install virtualenv
python -m virtualenv venv
venv/Scripts/activate
```
3. Install the dependencies
```
pip install -r requirements.txt
```
4. Run the development server:
```
setx FLASK_APP app.py
setx FLASK_ENV development
setx FLASK_DEBUG true
flask run --reload
```
5. Verify on the Browser: open http://127.0.0.1:5000/ and click `post a venue`.
- codespaces
1. open codespaces.
2. Initialize and activate a virtualenv using:
```
python -m virtualenv venv
source venv/bin/activate
```
3. Install the dependencies
```
pip install -r requirements.txt
```
5. Run the development server:
```
export FLASK_APP=app.py
export FLASK_ENV=development
export FLASK_DEBUG=true
flask run --reload
```
6.Verify on the Browser: open http://127.0.0.1:5000/ and click `post a venue`.

**Suggestion:**
In the fourth step of [Local Development](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#local-development), add instructions about “MySQL connection configuration” before `Flask run --reload`.
_For example:_
- Add MySQL connection configuration to the environment. 
```
export AZURE_MYSQL_USER=
export AZURE_MYSQL_PASSWORD=
export AZURE_MYSQL_HOST=
export AZURE_MYSQL_NAME=
export DEPLOYMENT_LOCATION=azure
```
- And in windows, add configuration using:
```
setx AZURE_MYSQL_USER user
setx AZURE_MYSQL_PASSWORD password
setx AZURE_MYSQL_HOST host
setx AZURE_MYSQL_NAME dbname
setx DEPLOYMENT_LOCATION azure
```

@john0isaac and @hemarina for notification.

**Comment by john0isaac** [comment]
I'm actually thinking of adding a dedicated heading for the DB as I intentionally didn't include these instructions because of a feature I implemented to make the website work without a database.

adding these instructions defeats the purpose of making the website able to work without a DB so, I will make it as an extra step if you want if not it will still work locally.
