### ISSUE TITLE
Spell error in readme

### ISSUE THREAD

**Issue by NanaXiong00** [john0isaac/flask-webapp-mysql-db#12]
**Describe the issue:**
In [README.md](https://github.com/john0isaac/flask-webapp-mysql-db?tab=readme-ov-file#deployment), are there any extra “w/” characters or other errors in the following pictures?

<img width="700" alt="image" src="https://github.com/john0isaac/flask-webapp-mysql-db/assets/138103031/2a0a1832-3ef0-4c99-916a-b5d893ae8ba5">

**Suggestion:**
Remove the "w/" characters.

@john0isaac and @hemarina for notification.

**Comment by john0isaac** [comment]
Intended not an error
It's an abbreviation for with
