### ISSUE TITLE
Use React for Frontend

### ISSUE THREAD

**Issue by john0isaac** [john0isaac/flask-webapp-mysql-db#2]
Change the whole frontend to React.

**Comment by HkSolDev** [comment]
Can you describe the issue is whole frontend to be in React

**Comment by john0isaac** [comment]
@MrBlackGhostt Done✅
Thank you for the note.
And yes, the whole frontend will be React.

**Comment by HkSolDev** [comment]
so it convert in react so in that i can help

**Comment by john0isaac** [comment]
@MrBlackGhostt  Thank you so much for showing interest, but the project is not currently accepting contributions!

**Comment by john0isaac** [comment]
Won't do for this repo.
